[zh]
languageName = "English"
contentDir = "content"
weight = 10
[zh.params]
languageISO = "CN"
languageTag = "zh-CN"
footer = 'Brought to you by <a class="text-muted" href="https://gethyas.com/">Hyas</a>'
alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'
